name: Swagger Docs

on:
  push:
    branches: [master]

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' 

      - name: Restore and Build
        run: |
          dotnet restore
          dotnet build --no-restore

      - name: Generate swagger.json
        run: |
          dotnet swagger tofile \
            --output swagger.json \
            ./BioGenomTestProject.dll v1

      - name: Install ReDoc CLI
        run: npm install -g redoc-cli

      - name: Generate HTML documentation with ReDoc
        run: redoc-cli bundle swagger.json -o docs/index.html

      - name: Upload docs artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: swagger-docs
          path: docs/index.html
